### ISSUE TITLE
单步预测

### ISSUE THREAD

**Issue by Miller-Xu** [NanakiC/LCDFormer#5]
我想用来做单步预测，修改参数num_for_predict=1。但output的T维度并不是1，所以我修改了decode
``` python
    def decode(self, trg, encoder_output, num_for_predict):
        output = self.decoder(self.trg_embed(trg), encoder_output)
        last_time_output = output[:,:,-num_for_predict:,:]
        return torch.squeeze(self.prediction_generator(last_time_output))
```
我用的是[https://github.com/zhiyongc/Graph_Convolutional_LSTM](url)的Seattle freeway network数据集，并和这篇论文的结果做了对比，发现LCDFormer并没有表现出更好的效果，甚至效果没那么好。
我使用[https://github.com/zhiyongc/Graph_Convolutional_LSTM](url)的FFR矩阵来代替adj_dtw作为输入，因为我发现这两个矩阵本质是一致的。
效果不如意是因为我的这些改动，还是说这个模型更适合做多步预测？

**Comment by NanakiC** [comment]
论文里有提到，LCDFormer自回归预测在初始的几步其实是不如其它几个模型。文中也有图片说明，另外我没有看Seattle freeway network这个数据集，如果是跨度较少并且节点不多的话，LCDFormer实际上并没有什么优势。
